version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/" # checks for workflow files in .github/workflows
    schedule:
      interval: "weekly"
