name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - site

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CXX: clang++
          CC: clang
